### ISSUE TITLE
May I have your username?

### ISSUE THREAD

**Issue by BloggerBust** [Nauci/test#1]
Hello Maintainer of Nauci,

I can see you have not used this repo in 2 years. I would really like to create a repo with nauci as the name. If you are not going to use this repo could we arrange for me to take the name? That would involve the following:

- You would need to rename your repo by following these instructions: https://help.github.com/articles/changing-your-github-username/
- You would need to email me at trevor.wilson@nauci.org and let me know that the username is available.

I would really appreciate it if you could do this for me seeing how you are not using this repo.

Thank you kindly,

Trevor Wilson

**Comment by Nauci** [comment]
I hadn't used it in two years or so but I am working on new projects now.

It's the handle I've been using across the internet for years now.

**Comment by BloggerBust** [comment]
Thanks for responding so quickly. I understand that you do not wish to part
with your username; just thought that I would ask.

It is a good name :-)

Cheers,

Trevor
